config/routes.rb
Rails.application.routes.draw do
  resources :users, only:[:edit, :update]
  resources :targets, only:[:new, :create, :edit, :update]
  resources :sales, only:[:new, :create, :edit, :update]
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root 'sales#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
  validates :time, numericality: { greater_than_or_equal_to: 7,
                                   less_than_or_equal_to: 22 }
end

app/models/target.rb
class Target < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :password, presence: true, length: { minimum: 8}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :home]
  include SalesHelper
  include SessionsHelper
  def home
    @today = data_of_a_day(Date.today)
    gon.today = @today
    @target = data_of_target(Date.today)
    gon.target = @target.sort_by { |a| a[:time] }
    @any_day = data_of_a_day()
    gon.any = Sale.new
  end

  def new
    @sale = Sale.new
  end

  def create
    @sale = Sale.create(sale_params)
  end

  def edit
    @sale = Sale.find(params[:id])
    
  end

  def update
    @sale = Sale.find(params[:id])
    if @sale.update(sale_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end
  
  private

    def sale_params
      params.require(:sale).permit(:price, :transactions, :total)
    end

    def logged_in_user
      unless logged_in?
        redirect_to login_url
      end
    end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user &.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path
    else
      flash.now[:danger] = '名前、またはパスワードが違います'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  def new
    @target = Target.new
  end

  def create
    @target = Target.new(trget_params)
    
    if @target.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @target = Target.find(params[:id])
  end

  def update
    @target = Target.find(params[:id])
    if @target.update(target_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private

    def target_params
      params.require(:target).permit(:date, :time, :price, :transactions, :total)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path
    else
      flash.now[:danger] = "8文字より短いです"
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
  def data_of_a_day(day = Date.yesterday)
    return Sale.where(date: day)
  end

  def data_of_target(day = Date.today)
    return Target.where(date: day)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "ホーム", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to current_user.name, edit_user_path(current_user) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィール", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalesApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= include_gon %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
</html>

app/views/sales/edit.html.erb
<h1 class="center"><%= @sale.date %>/<%= @sale.time %>時 </h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @sale do |f| %>
      <%= f.label :price, "単価" %>
      <%= f.number_field :price, class: 'form-control', id: "price" %>

      <%= f.label :transactions, "件数" %>
      <%= f.number_field :transactions, class: 'form-control', id: "transactions" %>

      <%= f.label :total, "時間帯別売上" %>
      <%= f.number_field :total, class: 'form-control', id: "total" %>

      <%= f.submit "確定", class: "btn btn-primary" %>
    <% end %>
    <%= link_to 'ホーム', root_path %>
    <script>
      $('#transactions').change(function() {
        var s = $('#price').val();
        var a = $('#transactions').val();
        var si = parseInt(s);
        var sa = parseInt(a);

        var total = si * sa

        $('#total').val(total)
      });
    </script>
  </div>
</div>

app/views/sales/home.html.erb
<%= render 'shared/graph_sales' %>

<%= render 'shared/today_sales' %>

<%= render 'shared/target' %>

<%= render 'shared/graph_difference' %>

<%= render 'shared/difference_today_target' %>

app/views/shared/_any_day.html.erb
<div>
  <h2><%= @any_day.first[:date] %></h2>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th class="center" scope="col">時間</th>
        <% 16.times do |num| %>
          <th class= "center" scope="col"><%= num + 7 %></th>
        <% end %>
        <th class="center" scope="col">合計</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th class="center" scope="row">件数</th>
        <% total = [] %>
        <% (7..22).each do |num| %>
          <td class="rigth" contentEditable = "true"><%= @any_day.find_by(time: num)[:transactions] %></td>
          <% total << @any_day.find_by(time: num)[:transactions] %>
        <% end %>
        <td class="rigth"><%= total.sum %></td>
      </tr>
      <tr>
        <th class="center" scope="row">単価</th>
        <% total = [] %>
        <% (7..22).each do |num| %>
          <td class="rigth" contentEditable = "true"><%= @any_day.find_by(time: num)[:price] %></td>
          <% total << @any_day.find_by(time: num)[:price] %>
        <% end %>
        <td class="rigth"><%= total.sum / total.length %></td>
      </tr>
      <tr>
        <th class="center" scope="row">時間別合計金額</th>
        <% total = [] %>
        <% (7..22).each do |num| %>
          <td class="rigth"><%= @any_day.find_by(time: num)[:total] %></td>
          <% total << @any_day.find_by(time: num)[:total] %>
        <% end %>
        <td class="rigth"><%= total.sum / total.length %></td>
      </tr>
      <tr>
        <th class="center" scope="row">累計金額</th>
        <% total = [] %>
        <% (7..22).each do |num| %>
          <% total << @any_day.find_by(time: num)[:total] %>
          <td class="rigth"><%= total.sum %></td>
        <% end %>
        <td class="rigth"><%= total.sum %></td>
      </tr>
    </tbody>
  </table>
  <input type="date" id="date">
  <input type="submit" id="submit" class="btn btn-primary" value="変更">
  <script>
    $('#date').change(function() {
      var day = $('#date').val();
    });
  </script>
</div>

app/views/shared/_difference_today_target.html.erb
<div>
  <h2>今日の目標と実利の差異</h2>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th class="center" scope="col">時間</th>
        <% (7..22).each do |num| %>
          <th class= "center" scope="col"><%= num %></th>
        <% end %>
        <th class="center" scope="col">合計</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th class="center" scope="row">件数</th>
        <% total = [] %>
        <% (7..22).each do |num| %>
          <% unless @target.find_by(time: num).nil? %>
            <% balance = @today.find_by(time: num)[:transactions] - @target.find_by(time: num)[:transactions]%>
            <% if balance < 0 %>
              <td class="rigth text-danger"><%= balance %></td>
            <%else%>
              <td class="rigth"><%= balance %></td>
            <% end %>
            <% total << balance %>
          <% end %>
        <% end %>
        <td class="rigth"><%= total.sum %></td>
      </tr>
      <tr>
        <th class="center" scope="row">単価</th>
        <% total = [] %>
        <% (7..22).each do |num| %>
          <% unless @target.find_by(time: num).nil? %>
            <% balance = @today.find_by(time: num)[:price] - @target.find_by(time: num)[:price] %>
            <% if balance < 0 %>
              <td class="rigth text-danger"><%= balance %></td>
            <%else%>
              <td class="rigth"><%= balance %></td>
            <% total << balance %>
            <% end %>
          <% end %>
        <% end %>
        <% unless total.length == 0 %>
          <td class="rigth"><%= total.sum / total.length %></td>
        <% end %>
      </tr>
      <tr>
        <th class="center" scope="row">時間別合計金額</th>
        <% total = [] %>
        <% (7..22).each do |num| %>
          <% unless @target.find_by(time: num).nil? %>
            <% today = @today.find_by(time: num)[:price] *  @today.find_by(time: num)[:transactions] %>
            <% target = @target.find_by(time: num)[:price] *  @target.find_by(time: num)[:transactions] %>
            <% if today - target < 0 %>
              <td class="rigth text-danger"><%= today - target %></td>
            <% else %>
              <td class="rigth"><%= today - target %></td>
            <% end %>
            <% total << today - target %>
          <% end %>
        <% end %>
        <% unless total.length == 0 %>
          <td class="rigth"><%= total.sum / total.length %></td>
        <% end %>
      </tr>
      <tr>
        <th class="center" scope="row">累計金額</th>
        <% total = [] %>
        <% (7..22).each do |num| %>
          <% unless @target.find_by(time: num).nil? %>
            <% today = @today.find_by(time: num)[:price] *  @today.find_by(time: num)[:transactions] %>
            <% target = @target.find_by(time: num)[:price] *  @target.find_by(time: num)[:transactions] %>
            <% total << today - target %>
            <% if total.sum < 0 %>
              <td class="rigth text-danger"><%= total.sum %></td>
            <% else %>
              <td class="rigth"><%= total.sum %></td>
            <% end %>
          <% end %>
        <% end %>
        <td class="rigth"><%= total.sum %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/shared/_graph_difference.html.erb
<h1>差異</h1>
  <canvas id="difference"></canvas>
  <script>
  var ctx = document.getElementById("difference");
  var difference = new Chart(ctx, {
    type: 'line',
    data: {
      labels: [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
      datasets: [
        {
          label: '時間帯別売上の差異',
          data: <% total = [] %>
                <% (7..22).each do |num| %>
                  <% today = @today.find_by(time: num)[:price] *  @today.find_by(time: num)[:transactions] %>
                  <% target = @target.find_by(time: num)[:price] *  @target.find_by(time: num)[:transactions] %>
                  <% total << today - target %>
                <% end %>
                <%= total %>,
          borderColor: "rgba(255,0,0,1)",
          backgroundColor: "rgba(0,0,0,0)"
        },
        {
          label: '累計売上の差異',
          data: <% array = [] %>
                <% (7..22).each do |num| %>
                  <% today = @today.find_by(time: num)[:price] *  @today.find_by(time: num)[:transactions] %>
                  <% target = @target.find_by(time: num)[:price] *  @target.find_by(time: num)[:transactions] %>
                  <% array << today - target %>
                <% end %>
                <% total = 0 %>
                <%= array.map{|i| total += i} %>,
          borderColor: "rgba(0,0,255,1)",
          backgroundColor: "rgba(0,0,0,0)"
        }
      ],
    },
    options: {
      title: {
        display: true,
        text: '今日の売上'
      },
      scales: {
        yAxes: [{
          ticks: {
            suggestedMax: 150000,
            suggestedMin: -100000,
            stepSize: 30000,
            callback: function(value, index, values){
              return  value
            }
          }
        }]
      },
    }
  });
  </script>

app/views/shared/_graph_sales.html.erb
<div class="center">
  <h1>当日の実利と目標</h1>
  <canvas id="myLineChart"></canvas>
  <script>
  var ctx = document.getElementById("myLineChart");
  var myLineChart = new Chart(ctx, {
    type: 'line',
    data: {
      labels: [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
      datasets: [
        {
          label: '売上',
          data: <% total = [] %>
                <% (7..22).each do |num| %>
                  <% total << @today.find_by(time: num)[:price] *  @today.find_by(time: num)[:transactions] %>
                <% end %>
                <%= total %>,
          borderColor: "rgba(255,0,0,1)",
          backgroundColor: "rgba(0,0,0,0)"
        },
        {
          label: '目標',
          data: <% total = []%>
                <% (7..22).each do |num| %>
                  <% unless @target.find_by(time: num).nil? %>
                    <% total << @target.find_by(time: num)[:price] *  @target.find_by(time: num)[:transactions]%>
                  <% end %>
                <% end %>
                <%= total %>,
          borderColor: "rgba(0,0,255,1)",
          backgroundColor: "rgba(0,0,0,0)"
        },
      ],
    },
    options: {
      title: {
        display: true,
        text: '今日の売上'
      },
      scales: {
        yAxes: [{
          ticks: {
            suggestedMax: 150000,
            suggestedMin: 0,
            stepSize: 10000,
            callback: function(value, index, values){
              return  value
            }
          }
        }]
      },
    }
  });
  </script>
</div>

app/views/shared/_target.html.erb
<div>
  <h2>今日の目標</h2>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th class="center" scope="col">時間</th>
        <% 16.times do |num| %>
          <th class= "center" scope="col"><%= num + 7 %></th>
        <% end %>
        <th class="center" scope="col">合計</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th class="center" scope="row">件数</th>
        <% total = [] %>
        <% (7..22).each do |num| %>
          <% unless @target.find_by(time: num).nil? %>
            <td class="rigth" contentEditable = "true"><%= @target.find_by(time: num)[:transactions] %></td>
            <% total << @target.find_by(time: num)[:transactions] %>
          <% end %>
        <% end %>
        <td class="rigth"><%= total.sum %></td>
      </tr>
      <tr>
        <th class="center" scope="row">単価</th>
        <% total = [] %>
        <% (7..22).each do |num| %>
          <% unless @target.find_by(time: num).nil? %>
            <td class="rigth" contentEditable = "true"><%= @target.find_by(time: num)[:price] %></td>
            <% total << @target.find_by(time: num)[:price] %>
          <% end %>
        <% end %>
        <% unless total.length == 0 %>
          <td class="rigth"><%= total.sum / total.length %></td>
        <% end %>
      </tr>
      <tr>
        <th class="center" scope="row">時間別合計金額</th>
        <% total = [] %>
        <% (7..22).each do |num| %>
          <% unless @target.find_by(time: num).nil? %>
            <td class="rigth"><%= @target.find_by(time: num)[:price] *  @target.find_by(time: num)[:transactions] %></td>
            <% total << @target.find_by(time: num)[:price] *  @target.find_by(time: num)[:transactions] %>
          <% end %>
        <% end %>
        <% unless total.length == 0 %>
          <td class="rigth"><%= total.sum / total.length %></td>
        <% end %>
      </tr>
      <tr>
        <th class="center" scope="row">累計金額</th>
        <% total = [] %>
        <% (7..22).each do |num| %>
          <% unless @target.find_by(time: num).nil? %>
            <% total << @target.find_by(time: num)[:price] *  @target.find_by(time: num)[:transactions] %>
            <td class="rigth"><%= total.sum %></td>
          <% end %>
        <% end %>
        <td class="rigth"><%= total.sum %></td>
      </tr>
    </tbody>
  </table>
  <% if current_user.admin? %>
    <input type="submit" id="new" value="新規作成" class="btn btn-primary">
    <script>
      var btn_target = document.getElementById("new")
      var myfunc_target = function(){
        location.href = `/targets/new`
      }
      btn_target.onclick = myfunc_target;
    </script>
    <input type="number" id="time_target" value="">
    <input type="submit" id="tar" value="確定" class="btn btn-primary">
    <script>
      var tar = document.getElementById("tar")
      var targetfunc = function(){
        var time_target = document.getElementById("time_target").value ;
        var num = time_target - 7
        var id = gon.target[num]["id"]
        location.href = `/targets/${id}/edit`
      }
      tar.onclick = targetfunc;
    </script>
  <% end %>
</div>

app/views/shared/_today_sales.html.erb
<div>
  <h2><%= @today.first[:date] %></h2>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th class="center" scope="col">時間</th>
        <% 16.times do |num| %>
          <th class= "center" scope="col"><%= num + 7 %></th>
        <% end %>
        <th class="center" scope="col">合計</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th class="center" scope="row">件数</th>
        <% total = [] %>
        <% (7..22).each do |num| %>
          <td class="rigth" contentEditable = "true"><%= @today.find_by(time: num)[:transactions] %></td>
          <% total << @today.find_by(time: num)[:transactions] %>
        <% end %>
        <td class="rigth"><%= total.sum %></td>
      </tr>
      <tr>
        <th class="center" scope="row">単価</th>
        <% total = [] %>
        <% (7..22).each do |num| %>
          <td class="rigth" contentEditable = "true"><%= @today.find_by(time: num)[:price] %></td>
          <% total << @today.find_by(time: num)[:price] %>
        <% end %>
        <td class="rigth"><%= total.sum / total.length %></td>
      </tr>
      <tr>
        <th class="center" scope="row">時間別合計金額</th>
        <% total = [] %>
        <% (7..22).each do |num| %>
          <td class="rigth"><%= @today.find_by(time: num)[:total] %></td>
          <% total << @today.find_by(time: num)[:total] %>
        <% end %>
        <td class="rigth"><%= total.sum / total.length %></td>
      </tr>
      <tr>
        <th class="center" scope="row">累計金額</th>
        <% total = [] %>
        <% (7..22).each do |num| %>
          <% total << @today.find_by(time: num)[:total] %>
          <td class="rigth"><%= total.sum %></td>
        <% end %>
        <td class="rigth"><%= total.sum %></td>
      </tr>
    </tbody>
  </table>
  <% if current_user.admin? %>
    <input type="number" id="time" value="">
    <input type="submit" id="btn" value="確定">
    <script>
      var btn = document.getElementById("btn")
      var myfunc = function(){
        var time = document.getElementById("time").value ;
        var num = time - 7
        var id = gon.today[num]["id"]
        location.href = `/sales/${id}/edit`
      }
      btn.onclick = myfunc;
    </script>
  <% end %>

  
</div>

app/views/targets/edit.html.erb
<h1 class="center"><%= @target.date %>/<%= @target.time %>時 </h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @target do |f| %>
      <%= f.label :price, "単価" %>
      <%= f.number_field :price, class: 'form-control', id: "price"%>

      <%= f.label :transactions, "件数" %>
      <%= f.number_field :transactions, class: 'form-control', id: "transactions" %>

      <%= f.label :total, "時間帯別売上" %>
      <%= f.number_field :total, class: 'form-control', id: "total" %>

      <%= f.submit "確定", class: "btn btn-primary" %>
    <% end %>
    <%= link_to 'ホーム', root_path %>
    <script>
      $('#transactions').change(function() {
        var s = $('#price').val();
        var a = $('#transactions').val();
        var si = parseInt(s);
        var sa = parseInt(a);

        var total = si * sa

        $('#total').val(total)
      });
    </script>
  </div>
</div>

app/views/targets/new.html.erb
<h1 class="center"><%= Date.today %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @target do |f| %>
      <%= f.label :date, "日付" %>
      <%= f.date_field :date, class: 'form-control', value: Date.today %>

      <%= f.label :time, "時間帯" %>
      <%= f.number_field :time, class: 'form-control' %>

      <%= f.label :price, "単価"%>
      <%= f.number_field :price, class: 'form-control', id: 'price' %>

      <%= f.label :transactions, "件数" %>
      <%= f.number_field :transactions, class: 'form-control', id: 'transactions' %>

      <%= f.label :total, "時間帯別売上" %>
      <%= f.number_field :total, class: 'form-control', id: "total" %>

      <%= f.submit "確定", class: "btn btn-primary" %>
    <% end %>
    <%= link_to 'ホーム', root_path %>
    <script>
      $('#transactions').change(function() {
        var s = $('#price').val();
        var a = $('#transactions').val();
        var si = parseInt(s);
        var sa = parseInt(a);

        var total = si * sa

        $('#total').val(total)
      });
    </script>
  </div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2><%= @user.name %></h2>
    <%= form_with(model: @user, local: true) do |f| %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "変更", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>